version: 2.1

orbs:
  slack: circleci/slack@3.4.3

executors:
   my-executor:
    docker:
      - image: circleci/ruby:2.5.8-node-browsers

jobs:
  test:
    executor: my-executor
    steps: 
      - checkout 

      - restore_cache:
          name: cache lord
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run: 
         name: bundle install  
         command: bundle check --path=vendor/bundle || bundle install --path vendor/bundle --clean --jobs 4 --retry 3

      - save_cache:
          name: save cache
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run: 
           name: bundle exec rake spec
           command: bundle exec rake spec
      
      - slack/status:
          success_message: ':circleci-pass: $CIRCLE_BRANCH のテストが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のテストが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

workflows:
  version: 2
  test-:
    jobs:
      - test